### ISSUE TITLE
YouTube iOS app cannot stream to OSMC via AirPlay

### ISSUE THREAD

**Issue by probonopd** [samnazarko/osmc#101]
YouTube iOS app cannot stream to osmc via AirPlay

I am using the most recent YouTube iOS app 2.16.11441-pre app on an iPhone 6 with the latest iOS 8.1.3, and I am running OSMC 0.0.4 on Raspberry Pi 2 Model B.

**Comment by probonopd** [comment]
I also filed an upstream ticket at http://trac.kodi.tv/ticket/15795 since I get the same behavior using OpenELEC 5.0.3 on the same hardware.

**Comment by DBMandrake** [comment]
Good luck with getting that fixed. Please check the Kodi forum where you will find many comments in many threads by Memphiz (Kodi Airplay developer) that it is impossible to fix this problem. The only solution is if google change their iOS app, which is extremely unlikely as it has been like this for over a year now.

The Kodi devs are fully aware of this issue as it is constantly brought up in their forum, but your trac ticket is likely to be closed or ignored as there is no solution.
