### ISSUE TITLE
iOS Photos app can only send pictures, not video using AirPlay

### ISSUE THREAD

**Issue by probonopd** [samnazarko/osmc#102]
The iOS Photos app can only send pictures, not video using AirPlay to OSMC.
When I try to play a video, it freezes.

I am using the most recent YouTube iOS app 2.16.11441-pre app on an iPhone 6 with the latest iOS 8.1.3, and I am running OSMC 0.0.4 on Raspberry Pi 2 Model B.

**Comment by samnazarko** [comment]
Use YouTube from Safari. This is not an issue: YouTube have changed the application codec.

**Comment by probonopd** [comment]
Thanks. What do you mean by "This is not an issue"? If you think this is a feature request rather than a bug, then please reopen this as a feature request. I was hoping AirPlay would work on OSMC just as seamless as on Apple hardware.

**Comment by samnazarko** [comment]
This is not an issue with OSMC. This is also not Apple hardware. You should look at getting these fixes implemented upstream.

**Comment by probonopd** [comment]
Thanks, opened a ticket on http://trac.kodi.tv/ticket/15795
