### ISSUE TITLE
Announce SSH and SFTP services via Zeroconf/Avahi by default

### ISSUE THREAD

**Issue by probonopd** [samnazarko/osmc#103]
The following files enable SSH and SFTP to be announced via Zeroconf/Avahi, so that one can log in over ssh from OS X Terminal without having to manually search for the IP address. Please install these files by default when SSH/SFTP services are enabled on the machine.

The `/etc/avahi/services/ssh.service` file is:

```
<?xml version="1.0" standalone='no'?>
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">
<service-group>
  <name replace-wildcards="yes">%h</name>
  <service>
    <type>_ssh._tcp</type>
    <port>22</port>
  </service>
</service-group>
```

Similarly, `/etc/avahi/services/sftp.service`wil announce the SFTP service:
```
<?xml version="1.0" standalone='no'?>
 <!DOCTYPE service-group SYSTEM "avahi-service.dtd">
 <service-group>
   <name replace-wildcards="yes">%h</name>
   <service>
     <type>_sftp-ssh._tcp</type>
     <port>22</port>
     <txt-record>path=/path/to/be/accessed</txt-record>
     <txt-record>u=osmc</txt-record>
   </service>
 </service-group>
```

**Comment by samnazarko** [comment]
Thanks. This is now in:

4198ba9

**Comment by probonopd** [comment]
Thank you very much! Makes osmc friendlier to use "out of the box".

**Comment by samnazarko** [comment]
You are welcome. Also added this for FTP and will do so for Samba

S
