### ISSUE TITLE
lirc_rpi.ko not working on Raspberry Pi 2 Model B

### ISSUE THREAD

**Issue by probonopd** [samnazarko/osmc#104]
I am trying to use LIRC with OSMC on the Raspberry Pi 2 Model B in order to control the media center via infrared remote control. However, the kernel module is not loaded. 

Following http://openelec.tv/forum/124-raspberry-pi/75336-rpi2-lirc-help, I changed `/boot/config.txt` to include `dtoverlay=lirc-rpi-overlay` and rebooted, but the `lirc_rpi.ko` does not get loaded.

It would be nice if lirc_rpi would be set up (and readily working) by default, since probably many people want to attach an infrared receiver to their media center Raspberry Pi.

**Comment by samnazarko** [comment]
This will be resolved in the next build and loaded by default

Sam

**Comment by probonopd** [comment]
When I do the following:

```
osmc@osmc:~$ sudo modprobe lirc_rpi
osmc@osmc:~$ dmesg | grep lirc
[  413.725828] lirc_dev: IR Remote Control driver registered, major 247 
[  413.728443] lirc_rpi: module is from the staging directory, the quality is unknown, you have been warned.
[  414.686843] lirc_rpi: auto-detected active low receiver on GPIO pin 18
[  414.687200] lirc_rpi lirc_rpi.0: lirc_dev: driver lirc_rpi registered at minor = 0
[  414.687212] lirc_rpi: driver registered!
[  414.849821] input: lircd as /devices/virtual/input/input2
```

then the kernel module is loaded, but `irw` seems to receive nothing. I have attached the receiver to pin 18.

**Comment by samnazarko** [comment]
I will re-open this.

We have reworked remotes a lot. I suggest we keep it open and you revisit this after the next build

Sam

**Comment by DBMandrake** [comment]
Make sure you run update to get the latest updates as a lot of changes have been made since Alpha 4 in the area of IR remote support.

I suggest you open a new thread at https://discourse.osmc.tv/ as github issues is really for bug reports not troubleshooting assistance.

**Comment by probonopd** [comment]
OK, got it to work: The lirc_rpi kernel module was not inserted automatically for me, so I had to add `modprobe lirc_rpi` to `/usr/bin/mediacenter`.

Then after a reboot I could do

```
sudo kill $(pidof lircd)
mode2 -d /dev/lirc0 # press keys to see some output
```
From there I could basically follow http://forum.osmc.tv/showthread.php?tid=6201&pid=116497#pid116497

**Comment by samnazarko** [comment]
No longer an issue
