### ISSUE TITLE
Wrong colors of Windows 7 installer if theme is changed

### ISSUE THREAD

**Issue by KONEY** [samnazarko/osmc#107]
![problem](https://cloud.githubusercontent.com/assets/5889626/6355487/aed1f874-bc56-11e4-8fff-96261b65a10b.png)

Not much to say, the screenshot is quite explanatory :) Not really a bug, but colors are quite difficult to read. Should either force both foreground and backgrond or none or them.

**Comment by samnazarko** [comment]
Can't replicate this. Please provide a theme file I can try to see what the issue is.

I tried a fix (you can try the new EXE) from the OSMC website, but I doubt it will resolve the problem. I need to be able to reproduce this myself ideally if we want to fix this.

**Comment by KONEY** [comment]
no problem! Just need to figure out how to attach files :)

**Comment by KONEY** [comment]
Can I have your email?

**Comment by samnazarko** [comment]
I can now replicate this.

I'll have a chat with @srmo as we seem to disagree about whether the background should inherit from the OS or not

S

**Comment by samnazarko** [comment]
This should be fixed as of https://github.com/samnazarko/osmc/commit/762563c. 

Can you re-download the Windows installer and test?

Sam

**Comment by KONEY** [comment]
Now it works, good job ;)

**Comment by samnazarko** [comment]
Thank @srmo.

Closed

**Comment by KONEY** [comment]
May I ask the reason why the background should have been inherited, when the text color isn't?

**Comment by samnazarko** [comment]
It's not meant to be inherited, it's meant to be 240,240,240 rgb

**Comment by srmo** [comment]
Exactly that was the problem.

**Comment by KONEY** [comment]
I was referring at the disagreement you mentioned before :)

**Comment by samnazarko** [comment]
We were actually discussing a combo box background layer which looks different on some platforms such as OS X.
