### ISSUE TITLE
Broadcomm Bluetooth Adapters RPi2

### ISSUE THREAD

**Issue by squallor** [samnazarko/osmc#109]
Out of the box I had problems with a broadcomm usb bluetooth adapter.

Turns out I needed to install the libbluetooth3 package separately, as it wasn't included in the bluez install.

I am still working through some of the service start issues, but I figured you might want to include that package in the next release.

**Comment by samnazarko** [comment]
If bluez is installed but libbluetooth3 isn't, then it means it's not a dependency of bluez. What are you trying to do with Bluetooth, as this is likely bringing in your dependency here.

dmesg output of your adapter too please

**Comment by squallor** [comment]
Trying to connect a ps3 remote at the moment.

I only know dmesg for the entire kernel buffer. Is there a way to filter to just a specific adapter?

**Comment by samnazarko** [comment]
The whole dmesg is fine, chuck it on paste.osmc.io

**Comment by squallor** [comment]
Just copied and saved it.

**Comment by squallor** [comment]
Ended up returning the broadcomm adapater because even in debian wheezy it was randomly disconnected. I did buy a cambridge silicon adapter to play with instead.

While there are no libbluetooth3 issues, I did find that rfkill is blocking bluetooth by default... since I am a bit of a linux amateur, I am still figuring out how to fix that without a startup script, but I figured you might want to know.

Feel free to close out this issue, however.

**Comment by samnazarko** [comment]
Can you put the dmesg output up, I'm still curious

>While there are no libbluetooth3 issues

Are you saying libbluetooth3 is *not* a dependency?

>I did find that rfkill is blocking bluetooth by default... since I am a bit of a linux amateur, I am still >figuring out how to fix that without a startup script, but I figured you might want to know.

My understanding is connmanctl overrides rfkill, and connmanctl enable bluetooth is enough to prevent rfkill.

**Comment by squallor** [comment]
latest dmesg in paste.osmc.io

I guess not? I tested libbluetooth3 just because I had the bluetooth adapter working in wheezy, but not in your alpha4 release and I was dif'ing packages. When I made the first post I had bluetooth up and discovering devices, but when I rebooted the next day it was down again and I never got it working after that. 

Like I said, even in stock debian I was having issues discovering it as a usb device even before trying to scan the bluetooth network, which is why I returned it and bought a different one. Besides that, I have been reading around that people have had issues with broadcomm usb bluetooth devices, which is why I switched to a cambridge silicon adapter.

I just tested "connmanctol enable bluetooth" with no luck. I also pasted my steps enabling bluetooth through the standard service command with rfkill  showing how I at least got the device being discovered (I haven't tried connecting anything to it, and I probably won't until later this week. I will keep you posted if I find anything of interesting, though).

 Let me know if there is anything else I can help with!

**Comment by squallor** [comment]
Also forgot to mention, that I have --noplugin=sap for bluetooth startup arguments. SAP seems to fail otherwise. My understanding is it is only for GPS? so I ignored it.

**Comment by samnazarko** [comment]
we still need a link to that dmesg

**Comment by squallor** [comment]
Sorry, tried to leave the dmesg before the info on rfkill
