### ISSUE TITLE
potential bug in qt_target_installer

### ISSUE THREAD

**Issue by l10n2jud4** [samnazarko/osmc#111]
It seems to me that there is a problem in mainwindow.cpp arround lines 140-157.
If user want to use nfs with a static ip, network will not be bring up !

**Comment by samnazarko** [comment]
You are right. Please take a look at 943fd2621b9a7b6f97eec45fa7321425b47b1590 which should fix this.

**Comment by l10n2jud4** [comment]
yes ;)

**Comment by samnazarko** [comment]
Closed. Please re-open if this is an issue in the next release.
