### ISSUE TITLE
settings in /etc/udisks-glue.conf do not have any effect

### ISSUE THREAD

**Issue by henini** [samnazarko/osmc#114]
I have tried to change the dmask and fmask for disks automounted by udisks to have "rw" permissions for group and "r" for other. To achieve this for all disks I have changed the file /etc/udisks-glue.conf as follows, which used to work in raspbmc.

>     automount_options = { sync, noatime, dmask=0002, fmask=0113 }
>     post_insertion_command = "udisks --mount %device_file --mount-options sync,noatime,dmask=0002,fmask=0113"

**Comment by samnazarko** [comment]
I think we once discovered this is because this runs on the device / block level rather than the partition level.

**Comment by samnazarko** [comment]
Was fixed in RC2
