### ISSUE TITLE
Power off not working

### ISSUE THREAD

**Issue by Dmole** [samnazarko/osmc#120]
UI freezes,  nothing happens for hours, but ssh works. nothing related in system or kodi logs

**Comment by Dmole** [comment]
Version:
uname -a
Linux osmc 3.18.5-2-osmc #1 PREEMPT Sun Feb 1 18:32:16 UTC 2015 armv6l GNU/Linux

Log:
nothing related in /home/osmc/.kodi/temp/kodi.log /var/log/*

**Comment by samnazarko** [comment]
uname -a is not the OSMC version. I will assume you are on Alpha 4. We have done a lot of work on this for the next release. Please open if still an issue.

>nothing related in /home/osmc/.kodi/temp/kodi.log /var/log/*

You should let us decide the relevance..

**Comment by Dmole** [comment]
Please help us help you by adding a "information to include in a bug report" in the documentation https://osmc.tv/help/wiki

I have no idea where the OSMC version is listed but yes it was Alpha 4.

cat /home/osmc/.kodi/temp/kodi.log | grep Platform
05:19:22 T:3024936960  NOTICE: Starting Kodi (14.1 Git:Unknown). Platform: Linux ARM 32-bit

all 982 lines:
http://pastebin.com/UH2q1Myj

grep -v "No information found" /home/osmc/.kodi/temp/kodi.log  | grep -v "DVDPlayer: Opening" |wc -l
982
