### ISSUE TITLE
no music scanner option

### ISSUE THREAD

**Issue by Dmole** [samnazarko/osmc#121]
no music scanner option = music i can only be accessed via files no DB things like music by year

**Comment by Dmole** [comment]
Version:
uname -a
Linux osmc 3.18.5-2-osmc #1 PREEMPT Sun Feb 1 18:32:16 UTC 2015 armv6l GNU/Linux

Log:
related in /home/osmc/.kodi/temp/kodi.log /var/log/*
09:53:59 T:2776626208  NOTICE: My Music: Scanning for music info using worker thread, operation took 08:41
only the music directory took more than a week to scan on raspbmc

**Comment by samnazarko** [comment]
Please stop spamming our GitHub with opening multiple issues.

**Comment by Dmole** [comment]
Is there a better way to report bugs or do you not what to hear about them?
Maybe you should say something in the documentation about what you want.

**Comment by samnazarko** [comment]
Please be respectful. You have opened three GitHub reports and a lot of comments which will result in mail sent to everyone subscribed to this repository.

I do care about bugs, however I do believe they are fixed. I am encouraging you to open the issue *only* if the issue persists on the Release Candidate build which is due shortly. 

Your reports have been nowhere near verbose enough for any real investigation to be done. In the future, please us the forum at https://discourse.osmc.tv and verifying you are indeed experiencing a bug before escalating it to this issue tracker

S
