### ISSUE TITLE
Movies main manue item sub options all fail

### ISSUE THREAD

**Issue by Dmole** [samnazarko/osmc#122]
select, info, and title buttons all don't work

**Comment by samnazarko** [comment]
* Version?
* Log?
* More verbose description?

Re-open with a proper bug report.

**Comment by Dmole** [comment]
Version:
uname -a
Linux osmc 3.18.5-2-osmc #1 PREEMPT Sun Feb 1 18:32:16 UTC 2015 armv6l GNU/Linux

Log:
nothing related in /home/osmc/.kodi/temp/kodi.log /var/log/*

More verbose description:
on the main menu there is an option called "movies", in that the android remote "info", and "title" buttons  don't do anything, and the select button just dumps you in another mist of movies instead of playing the movie.

please reopen this bug.
