### ISSUE TITLE
Wrong ownership of tvheadend configuration directory

### ISSUE THREAD

**Issue by akaihola** [samnazarko/osmc#129]
In alpha 4, after installing the `armv6l-tvheadend-app-osmc` package with `apt-get`, tvheadend fails to work because the directory `~/.hts/tvheadend` is owned by `root` and not writable by the `osmc` user.

**Comment by samnazarko** [comment]
Fixed in https://github.com/samnazarko/osmc/commit/b32d805e0304381831b8dda4ef6b60c77097e706
