### ISSUE TITLE
Kodi fails to load libraries from central MySQL database.

### ISSUE THREAD

**Issue by waterboyharris** [samnazarko/osmc#131]
I'm thinking about getting a Vero, so I'm trying out OSMC on my Pi. I'm using a central MySQL database. On some reboots it will load libraries from the database and other times it wont.  OpenElec had this problem several versions ago.  If Kodi starts before the network is up then it attempts connection to the database, fails and never retries.  They solved it by adding the option to wait for the network before starting Kodi.

**Comment by DBMandrake** [comment]
Assuming you are running the Release candidate:

sudo systemctl enable connman-wait-for-network.service

This will make kodi wait for a network connection before loading. There should be a GUI setting for this by final release.

**Comment by waterboyharris** [comment]
Excellent! Thanks for the quick response.

**Comment by samnazarko** [comment]
This is now available via the GUI

Sam
