### ISSUE TITLE
WiFi adapter gets disabled

### ISSUE THREAD

**Issue by MogicK** [samnazarko/osmc#135]
I just installed the OSMC RC on a Raspberry Pi 2 B+. It has a small USB WiFi dongle and is also connected to a USB HDD.

When the device boots, WiFi works. Responds to ping, SSH, all of that. Definitely works. After a while though, it just gives up. All network traffic over WiFi just stops. The OSMC network panel still shows the WiFi adapter as enabled and connected to the correct network.

Here's a log. Hopefully it helps. http://paste.osmc.io/jupihiviko

**Comment by martinratinaud** [comment]
Same for me, connection seems to goes on and off

```
Request timeout for icmp_seq 53
ping: sendto: Host is down
Request timeout for icmp_seq 54
ping: sendto: Host is down
Request timeout for icmp_seq 55
ping: sendto: Host is down
Request timeout for icmp_seq 56
ping: sendto: Host is down
Request timeout for icmp_seq 57
Request timeout for icmp_seq 58
64 bytes from 192.168.1.200: icmp_seq=59 ttl=63 time=81.673 ms
Request timeout for icmp_seq 60
Request timeout for icmp_seq 61
Request timeout for icmp_seq 62
Request timeout for icmp_seq 63
Request timeout for icmp_seq 64
Request timeout for icmp_seq 65
Request timeout for icmp_seq 66
```

I have an EDIMAX - EW-7811UN - NANO ADAPTATEUR CLÉ USB SANS FIL - 150 MBPS which worked fine with the alpha4 release.

Tell me if you need some logs and thanks for your work

**Comment by thkrmr** [comment]
Experiencing issues with  EDIMAX - EW-7811UN too, it seems as if something changes between the last alpha release where it was working fine and the RC kernel. Connection gets dropped. On a Pi 2.

**Comment by martinratinaud** [comment]
Hi guys, any news on that ?

**Comment by DBMandrake** [comment]
A new kernel will be released soon with changes to the Wifi drivers, so this will hopefully solve this issue. It's working well for me so far during testing on an Edimax EW-7811UTC.

**Comment by martinratinaud** [comment]
Good,

will there be an update available or will we have to reinstall all from scratch ?

Thanks a lot anyway

**Comment by samnazarko** [comment]
This is already live. Should be able to upgrade from RC1 without issue.
