### ISSUE TITLE
Osmc randomly freezes

### ISSUE THREAD

**Issue by desean1625** [samnazarko/osmc#136]
Osmc freezes at random times or reboots. Running latest osmc updates with hippojays helix plexbmc. No log errors produced in .kodi/temp/kodi.log just freezes so it makes it hard to trouble shoot.

**Comment by desean1625** [comment]
No errors in /var/log/ does the OS log system level errors somewhere else?

**Comment by trex2000** [comment]
Unfortunately, I'm experiencing the same problem also myself. No relevant entries in the log, it just suddenly freezes.

**Comment by trex2000** [comment]
Could be an overcloking problem?

**Comment by DBMandrake** [comment]
Unfortunately as bug reports go "randomly freezes and no errors are logged" is completely useless to us. It's almost certainly a hardware issue like excessive overclock and not a software bug in OSMC.

Please open a new thread at http://discourse.osmc.tv to get some assistance troubleshooting this, as github issues is not an appropriate venue for hardware troubleshooting.

**Comment by desean1625** [comment]
Found the issue. It was caused by over clocking. If I set the settings higher then normal it wound happen when loading large amounts of content. I think it would require more power than the supply was providing but would freeze before it did the rainbow in the top corner. After I turned it down to normal it stopped freezing and does put the rainbow at the top right when loading content.

**Comment by DBMandrake** [comment]
The rainbow warning at the top right corner means the supply voltage is below the minimum acceptable level. So while it is no longer freezing your power adaptor or cable is still inadequate. You shouldn't be seeing the rainbow indicator at all.
