### ISSUE TITLE
Dose not detect D-link DWA-171 USB Wifi adapter

### ISSUE THREAD

**Issue by peso1** [samnazarko/osmc#143]
I try to install a D-Link DWA-171 USB Wifi in a Raspberry Pi 2.
It dose not get detected as a connected adapter.
When I connect my DWA-160 back again in the same USB slot everything works again.
Whan I connect the DWA-171 on my laptop it get connected as it should in my network.

Do you need any log file?
But as I say it dosen not get connected according to what I see in the GUI at OSMC RC.

**Comment by samnazarko** [comment]
Please post on discourse.osmc.tv and add a full system log
