### ISSUE TITLE
The Rasbmc website is cute but annoying

### ISSUE THREAD

**Issue by lendle** [samnazarko/osmc#152]
This may not be the right place to file an issue, but not sure where else to put it.

The [raspbmc website](www.raspbmc.com/) has a very nice fade in affect, but waiting for the link to osmc.tv to show up (12 seconds!) is agonizing. Please let the link appear immediately.

Use case: I forgot the name of osmc, so I just googled rasbmc because I knew I could find the link that way.

**Comment by marktheis** [comment]
Hi. Thank you for taking your time to write this issue.
I will remove the effect and make sure that any future visitors won't have to endure that.

**Comment by lendle** [comment]
Thanks!
