### ISSUE TITLE
Windows OSMC installer: wireless config validation requires refresh

### ISSUE THREAD

**Issue by leeds55** [samnazarko/osmc#154]
It appears that the installer doesn't re-enable the 'forward' control on entering an SSID & key if at first you fail to specify either.

Replication steps:
1. Start the Windows installer
2. Go to install on RPi, using RC2 (suspect this is irrelevant, but I'm trying to remember everything I did!)
3. State that OSMC should connect via wireless, WPA2, but don't specify SSID or key
4. Validation message appears
5. Enter SSID & key
6. You'll find that the forward key is still disabled.

**Comment by samnazarko** [comment]
This should be fixed in https://github.com/samnazarko/osmc/commit/e539b92300b11550ca15e809c5c9daf82305f80a

Sam

**Comment by leeds55** [comment]
Not surprised you're a midnight oil type. Like the notifications, hope you
feel like the team's efforts on OSMC are appreciated.
--
Rich Hims
leeds55@gmail.com

**Comment by srmo** [comment]
you beat me at 10 hours. damn.
