### ISSUE TITLE
Vero sets strange resolution when TV has been powered off

### ISSUE THREAD

**Issue by theailer** [samnazarko/osmc#155]
As per the title. After I power on my TV, a Sony bravia 3, the TV reports the resolution as 720p but it looks interlaced as hell and I can only make out a quarter of osmc's display. It's kind of like setting your resolution to 1024*768 but your monitor only displays 640*480 of it.

**Comment by samnazarko** [comment]
Hi

Can you please let me know your TV's native resolution?

Can you give me a Kodi log with debug support?

S

**Comment by theailer** [comment]
TV has full HD so I suppose native would be 1920x1080. I've uploaded the kodi.log using the built in osmc log uploader. I however restarted between logging and sending, maybe the log gets overwritten between reboots? I did make a copy of it before restarting that I can paste here if you want.

**Comment by theailer** [comment]
I've enabled debug and checked the logs and it doesn't log anything when I turn my TV on or off.

**Comment by samnazarko** [comment]
Should be resolved in RC3.

**Comment by theailer** [comment]
OK. Do you have an eta ?

fre 15 maj 2015 07:46 Sam Nazarko <notifications@github.com> skrev:

**Comment by samnazarko** [comment]
Scheduled for later today

**Comment by theailer** [comment]
Nice, one other iie have is that when I choose the vero on my TVs cec menu
it doesn't switch to the vero. It's maybe related to the above issue?

mån 18 maj 2015 08:08 Sam Nazarko <notifications@github.com> skrev:
