### ISSUE TITLE
OSMC does not run on SLICE

### ISSUE THREAD

**Issue by mdeiders** [samnazarko/osmc#159]
When will OSMC support FIVENINJAS SLICE?

**Comment by samnazarko** [comment]
I'm not sure.

A quick search leads me to believe @ghollingworth is working on dual boot, but I don't personally follow Slice development so he would have to fill you in

**Comment by ghollingworth** [comment]
Yes we have dual boot basically working correctly now, but it's going to take quite a while to get things like the codec working through OSMC because we first need to upstream our driver into the Raspberry Pi  kernels so it can be selected through the device tree in OSMC.  But assuming we have OSMC integrated into NOOBS then there's no reason it cannot be installed on Slice as well.

**Comment by samnazarko** [comment]
@mdeiders as Gordon says, there's not much preventing OSMC running on Slice (once we're in NOOBS -- NOOBS is in a bit of a state of flux at the moment as Pi2 compatibility is still not quite there). 

But to get it working properly, i.e. the PWM driver, automatic codec installation will take a bit longer. 

@ghollingworth is there a way to detect if we are running on a Compute Module programatically? Does /proc/cpuinfo differ (I assume 'Revision' will)? I ask because it would be ideal if we could preload the necessary Device Tree overlay automatically.

**Comment by ghollingworth** [comment]
The device tree overlay will be pushed into the build by the NOOBS software running on Slice and it'll modify config.txt to reference it.

The revision numbers in /proc/cpuinfo will indicate whether it is a compute module, although won't tell you which compute module design it is!

**Comment by samnazarko** [comment]
>The device tree overlay will be pushed into the build by the NOOBS software running on Slice and it'll modify config.txt to reference it.

We will need to take care there. We expect config.txt to be edited within OSMC's 'Pi config' option, so I will have to double-check that we handle existing definitions properly. CC @KODeKarnage. I suspect once we will also want some sanity checking: only make the DT option available in our config utility iff we are on a compute module. 

>The revision numbers in /proc/cpuinfo will indicate whether it is a compute module, although won't tell you which compute module design it is!

It would be nice if there was some way to tell, like putting a file on the fat partition called 'SLICE' which we can check at bootup. I suspect your PWM driver has some hooks in to Kodi, and if I am going to allow users to really utilise the LEDs you offer, I'll need to fopen() something when Kodi starts so I know if I'm meant to enable these effects. I don't particularly want to check loaded modules or #ifdef (that would require a separate build anyway)... I am just speculating here anyway, for all I know the LED ring is exposed as a /dev and you handle this all gracefully anyway in a nice diff that can be patched on to Kodi.

**Comment by KODeKarnage** [comment]
@samnazarko The Pi config module ignores dtoverlay entries it does not recognise. (More accurately, as the config.txt is rewritten every time a change is made, the unrecognised entries are saved, set aside, and then written back.)

I dont think anything would need to be done to the Pi config module unless you want to provide the user with the option to toggle a Slice-specific overlay (or edit a parameter).

**Comment by samnazarko** [comment]
Had another request for this by email.

Looks like FiveNinjas are violating the GPL: https://github.com/FiveNinjas/SliceOS/issues/12 -- I don't believe it myself, as two of their guys are working for the Pi foundation.

Will find out soon. @ghollingworth can you point us towards the Slice sources?

**Comment by mdeiders** [comment]
It's OK to mention another product here right? Anyway I wantedd OSMC!!!!

Based on OpenELEC 5.0
Based on Kodi 14.1

Stable OS release: http://updates.fiveninjas.com/slice/stable/Slice_RPi_System.tar.xz. 
NOOBS release: http://updates.fiveninjas.com/slice/noobs_test.zip we will need thiss
Slice skin (if anyone wants to use it on OSMC): http://www.filedropper.com/skinslice

the listed operating systems are at http://updates.fiveninjas.com/sliceos.json. 

this is why the SLICE is so much faster than the Pi 1!!! It's overclocked to shit!

> gpu_mem=160
> arm_freq=900
> core_freq=300
> sdram_freq=450

> over_voltage=4
> force_turbo=1

There is a file called 'dt-blob.bin'. This appears to control the lights? I used the official OSMC kernel but if you want the driver you can use the attached 'kernel.img' which appears to make the LEDs work on OSMC. Well not work but they get recognised i think. 

Anyway on how to get it on the SLICE:

1. Download http://updates.fiveninjas.com/slice/noobs_test.zip
2. Plug Slice USB into computer. Follow https://www.raspberrypi.org/documentation/hardware/computemodule/cm-emmc-flashing.md
3. Mount /dev/sda1
4. Now, download two OSMC boot files:
   http://46.37.189.135/osmc/download/installers/noobs/root-rbp1.tar.xz
   http://46.37.189.135/osmc/download/installers/noobs/boot-rbp1.tar.xz
5. Make a folder under os folder called 'osmc'
6. Copy those two files in there
7. Also download the following files and copy them in to osmc/ 
   https://raw.githubusercontent.com/samnazarko/osmc/master/installer/noobs/release_notes.txt
   https://raw.githubusercontent.com/samnazarko/osmc/master/installer/noobs/os-pi1.json
   https://raw.githubusercontent.com/samnazarko/osmc/master/installer/noobs/partitions.json
   https://raw.githubusercontent.com/samnazarko/osmc/master/installer/noobs/partition_setup.sh
8. Now unmount SLICE with umount /dev/sda1
9. Boot SLICE and select OSMC

The licenses will be copied over automatically so don't need a worry but you may want 2 add the overclock settings above

I din't get time to look at how to make remote properly yet but I use yatse on my iphone 5s and it works great.

see no problems eh

thx

**Comment by samnazarko** [comment]
I also received your email.

I would recommend people avoid this for now. I'm unsure of the ramifications of doing this, or if it even works properly.

I am closing this: seems that we don't need to do anything special to support Slice. And we are now in NOOBS as well: so not much to worry about there.

**Comment by ghollingworth** [comment]
Yeah, if you follow those instructions (using noobs_test.zip) then there�s
a good chance (about one in three) that you�ll brick your Slice.

That�s why it�s named test!!!

Gordon

**Comment by pepijn809** [comment]
Any way to get the "Slice" theme uploaded again? @mdeiders
