### ISSUE TITLE
"Name or service not known" when trying to access www.youtube.com from OSMC

### ISSUE THREAD

**Issue by Lx** [samnazarko/osmc#160]
When I try to either log into YouTube or play a video from within Kodi, a progress window shows for two full minutes followed by nothing.

* Both my OSMC installation and my Linux Mint desktop are on the same LAN, and both use DHCP.
* Pinging `youtube.com` succeeds from both an OSMC terminal and my desktop.
* Pinging `www.youtube.com` succeeds from my desktop, but **fails from an OSMC terminal**:

```
osmc@osmc:~$ ping -c 3 youtube.com
PING youtube.com (216.58.220.142): 56 data bytes
64 bytes from 216.58.220.142: seq=0 ttl=56 time=28.969 ms
64 bytes from 216.58.220.142: seq=1 ttl=56 time=28.404 ms
64 bytes from 216.58.220.142: seq=2 ttl=56 time=28.530 ms

--- youtube.com ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 28.404/28.634/28.969 ms
```

```
osmc@osmc:~$ time ping www.youtube.com
ping: bad address 'www.youtube.com'

real	1m32.578s
user	0m0.000s
sys	0m0.010s
```

```
osmc@osmc:~$ time wget -O /dev/null www.youtube.com
--2015-04-29 21:29:16--2015-04-29 21:32:10--  http://www.youtube.com/
Resolving www.youtube.com (www.youtube.com)... failed: Name or service not known.
wget: unable to resolve host address ‘www.youtube.com’

real	1m4.745s
user	0m0.040s
sys	0m0.020s
```

A debug log of me trying to play [a video](https://youtu.be/PpccpglnNf0) through Kodi is at http://paste.osmc.io/semutolapi.dos, but to me this issue seems to be at a deeper level than Kodi.

I'm running OSMC on a Raspberry Pi 2.

I'm happy to take direction on assisting further with the resolution of this issue.

**Comment by DBMandrake** [comment]
Can you open a new thread in our support forum at https://discourse.osmc.tv/ and paste everything you've provided above there ?

Github issues is not really suited for support and troubleshooting, and is meant for bug reports. 

Needless to say I can't reproduce the issue you describe so we need to do some troubleshooting of your DNS configuration and network setup to figure out what is happening here.

Thanks.

**Comment by Lx** [comment]
Thanks for the quick pointer in the right direction, @DBMandrake.  Discourse thread is [here](https://discourse.osmc.tv/t/name-or-service-not-known-when-trying-to-access-www-youtube-com-from-osmc/3555).
