### ISSUE TITLE
OSMC Installer for Mac OS: Error copying files to sdcard

### ISSUE THREAD

**Issue by pedrofernando94** [samnazarko/osmc#165]
I checked the log files and found out it does not work on mac os because dd command needs bs=1m to be changed to bs=1M ( the m needs to be M (capitalized). I installed on scared simply doing the command corrected in terminal no problem.

Log File for Reference:
```
seg Mai 4 00:38:34 2015 EULA has been accepted
seg Mai 4 00:38:34 2015 Downloading http://46.37.189.135/osmc/download/installers/diskimages/OSMC_TGT_rbp1_20150412.img.gz
seg Mai 4 00:38:36 2015 File claims to be already an 'img'. No need to extract.
seg Mai 4 00:38:36 2015 Requesting confirmation from user
seg Mai 4 00:38:38 2015 User confirmed
seg Mai 4 00:38:38 2015 going to start osa
seg Mai 4 00:38:38 2015 pasting admin script to process do shell script "dd if=/Users/utilizador/OSMC_TGT_rbp1_20150412.img of=/dev/rdisk4 bs=1m conv=sync && sync" with administrator privileges
seg Mai 4 00:38:38 2015 waiting for finish
seg Mai 4 00:38:41 2015 osa claims to be done...collect output and verify
seg Mai 4 00:38:41 2015 Imaging failed!
seg Mai 4 00:38:41 2015 Messages are:
seg Mai 4 00:38:41 2015 	 stdout: 
seg Mai 4 00:38:41 2015 	 stderr: 0:137: execution error: dd: invalid number `1m' (1)
```

**Corrected command in mac os would be:**
```
dd if=/Users/utilizador/OSMC_TGT_rbp1_20150412.img of=/dev/rdisk4 bs=1M conv=sync && sync
```

**Comment by samnazarko** [comment]
The correct dd argument is passed on OS X and we should be taking care of the difference between 1M and 1m already..

The OSX installer has been widely used before. I do not believe it should be 1M but rather 1m

Sam

**Comment by samnazarko** [comment]
Here is supporting evidence that lower m is needed for OSX: http://superuser.com/questions/421770/dd-performance-on-mac-os-x-vs-linux

**Comment by pedrofernando94** [comment]
Well if it works for most it is correct. Here i get Illegal numeric value if i use `bs=1m`... I have to use `bs=1M`. Thanks for responding so quickly ill be watching for other things i find.

**Comment by samnazarko** [comment]
What version of OSX? Have you installed anything like Macports or Homebrew?
