### ISSUE TITLE
libcec should be updated for Raspberry Pi bug fixes

### ISSUE THREAD

**Issue by CRCulver** [samnazarko/osmc#172]
As I write this, the version of libcec in osmc rc2 is 2.1.4. Some significant bug fixes for the Raspberry Pi came with libcec versions 2.2.0 and 3.0.0 (including one for my own television, currently unsupported on osmc). Could an update be pushed?

**Comment by samnazarko** [comment]
>osmc rc2 is 2.1.4

popcornmix fixes are backported. 3.x will ship with Isengard.

What behaviour are you experiencing that is fixed in a newer version?

**Comment by CRCulver** [comment]
According to [this issue](https://github.com/Pulse-Eight/libcec/issues/37) at libcec’s Github repository, a fix has been committed for Simplink on LG televisions.

**Comment by samnazarko** [comment]
This is old: we have built libCEC since Oct 2014 from top of tree, so any fixes there should be in already.

**Comment by CRCulver** [comment]
One of the participants in that thread writes "just tested with the upcoming libCEC 2.3.0 and it's working correctly now". So, I suspect this is something that went into 3.0.0.

**Comment by samnazarko** [comment]
Will keep an eye on it. We cannot bump to 3.x yet as it is not backportable to 14.x. At least this is my understanding after talking to @opdenkamp

**Comment by CRCulver** [comment]
The Kodi version in OSMC has now been upgraded to Isengard, but the libcec version remains 2.1.4. Why wasn't the libcec version upgraded along with Kodi as suggested earlier?

**Comment by samnazarko** [comment]
libCEC is 3.x. Where are you seeing 2.14?

**Comment by CRCulver** [comment]
Today, after coming back from holiday and seeing that the July OSMC update had arrived with Isengard, I updated OSMC from within the Kodi addon. According to aptitude, I continue to have only the libcec2 package installed, at version 2.1.4-2.

**Comment by DBMandrake** [comment]
Then provide a full debug log so we can see why your system has not updated properly - preferably in a new thread on http://discourse.osmc.tv as github issues is for bug reports not for troubleshooting.

The current version of libcec on OSMC is 3.0.0-4.

**Comment by samnazarko** [comment]
This is not a GitHub issue. Please post on our forum. This GitHub is for development issues only.

**Comment by samnazarko** [comment]
>the libcec2 package installed

OSMC does not version its libCEC package. If you have installed emulators or another package. This is the reason.

OSMC packages always have the suffix -osmc.

**Comment by CRCulver** [comment]
I’m well aware of what Github issues are for, and I don’t appreciate being chided for answering the question that Sam asked.

**Comment by samnazarko** [comment]
Please start a forum post and link us to it. Add dpkg -l too. I suspect you'll have installed an emulator or something similar from the forum.
