### ISSUE TITLE
Update fails with "unkown package error"

### ISSUE THREAD

**Issue by martinratinaud** [samnazarko/osmc#176]
Hi guys,

I tried to update OSMC from the GUI and got the following error: `an error occurred while installing the following package: unknown package`

I'm not sure where to find the logs and my kodi verison is 14.1 (which I do not if it is RC or another one)

Thanks for your help

**Comment by DBMandrake** [comment]
Please use the log uploader in OSMC settings to upload your full logs.

**Comment by martinratinaud** [comment]
Done http://paste.osmc.io/uritemimac

**Comment by martinratinaud** [comment]
any idea ?

**Comment by samnazarko** [comment]
This is a bug tracker and is not intended for user support. Please start a forum post and we will do our best to help there. Upload full logs.
