### ISSUE TITLE
Upgrade to latest stable tvheadend version

### ISSUE THREAD

**Issue by krotof1a** [samnazarko/osmc#177]
tvheadend has now upgraded its stable version to 4.0.2.
Could you update the build to reference it ?
I am not able to build it by myself, but I can test a RPI2 package if necessary.

Thanks for your great work !

**Comment by krotof1a** [comment]
May I ask why it is invalid ? Upgrading to the latest stable version may bring new functionalities (like RTSP IPTV support) and fix some issues. Current used version 3.9 was an unstable snapshot.
I have compiled v4.0.2 manually on RPI2 (using tvheadend's git and make mechanism - as I don't know how to use OSMC one) and it works just fine. So for me it's done, but it could be useful for others.

Regards.

**Comment by samnazarko** [comment]
Because OSMC aggressively tracks upstream and this will be done for final

I thought I had left a comment, my mistake.

Sam

**Comment by krotof1a** [comment]
Ok. Thanks for the answer.
