### ISSUE TITLE
Addons slow to launch and run

### ISSUE THREAD

**Issue by ErenPhayte** [samnazarko/osmc#182]
Addons take forever to load. Sometimes unresponsive. Example would be sound cloud. If I got to site or use API it's fast. However through OSMC the plugin is extremely slow.

I have several plugin that are also none responsive or slow to launch including OSMC settings addons (enabled by default).

**Comment by DBMandrake** [comment]
Please open a thread on our forum at http://discourse.osmc.tv and provide full debug logs demonstrating the issue and provide as much information as you can about the problem. Github issues is for reporting confirmed bugs not for support and troubleshooting assistance.
