### ISSUE TITLE
Wireless not auto-connecting when wired

### ISSUE THREAD

**Issue by Mustack** [samnazarko/osmc#185]
I've setup my pi2 OSMC box to stream from a samba share over a wired connection but I get my internet over wifi. I can set this up by connecting to Wifi and setting a default gateway on that network but not on the wired network. The problem is that every time OSMC reboots, it connects to the wired connection, assigns the default gateway that should be on the wireless network and doesn't connect to the wireless network. The fix is to manually connect to my Wifi network and enter the default gateway again.

**Comment by samnazarko** [comment]
I believe that we only connect to one technology at a time (preferred). You could change this in your ConnMan configuration. I don't believe that this is a bug.

**Comment by Mustack** [comment]
Thanks for your attention on this issue. If there's a way to configure it in OSMC, shouldn't there be a way to persist that configuration and re-apply it at startup? It seems like a bug from the user perspective. I'm a technical guy. I can probably look into ConnMan and learn how to solve my own issue but if OSMC is for mass consumption, it might be a low-impact bug to consider investigating.

**Comment by DBMandrake** [comment]
You can change the preferred network order in /etc/connman.conf but connman will by design not auto connect multiple interfaces on boot - this is not something we can change without source code patches to connman as there are no configuration options to auto connect multiple interfaces.
