### ISSUE TITLE
Can't update bootloader package

### ISSUE THREAD

**Issue by 2senel** [samnazarko/osmc#75]
Unpacking rbp-bootloader-osmc (1.0-3) over (1.0-2) ...
dpkg: error processing archive /var/cache/apt/archives/rbp-bootloader-osmc_1.0-3_armhf.deb (--unpack):
 unable to make backup link of `./boot/start_x.elf' before installing new version: Operation not permitted

**Comment by 2senel** [comment]
Fixed

**Comment by samnazarko** [comment]
Good to hear, thanks for keeping me posted.
