### ISSUE TITLE
Still can`t update kernel via apt-get

### ISSUE THREAD

**Issue by 2senel** [samnazarko/osmc#80]
Nastavuje se balík rbp-image-3.18.3-osmc (1) …
Running depmod.
Examining /etc/kernel/postinst.d.
run-parts: executing /etc/kernel/postinst.d/apt-auto-removal 3.18.3-osmc /boot/vmlinuz-3.18.3-osmc
run-parts: executing /etc/kernel/postinst.d/inform-updater 3.18.3-osmc /boot/vmlinuz-3.18.3-osmc
run-parts: executing /etc/kernel/postinst.d/initramfs-tools 3.18.3-osmc /boot/vmlinuz-3.18.3-osmc
run-parts: executing /etc/kernel/postinst.d/process-vmlinuz-rbp 3.18.3-osmc /boot/vmlinuz-3.18.3-osmc
run-parts: /etc/kernel/postinst.d/process-vmlinuz-rbp exited with return code 1
Failed to process /etc/kernel/postinst.d at /var/lib/dpkg/info/rbp-image-3.18.3-osmc.postinst line 391.
dpkg: chyba při zpracovávání balíku rbp-image-3.18.3-osmc (--configure):
 podproces instalovaný post-installation skript vrátil chybový status 2
dpkg: nesplněné závislosti zamezily konfiguraci balíku rbp-kernel-osmc:
 rbp-kernel-osmc závisí na rbp-image-3.18.3-osmc; avšak:
  Balík rbp-image-3.18.3-osmc zatím není zkonfigurován.

dpkg: chyba při zpracovávání balíku rbp-kernel-osmc (--configure):
 problém se závislostmi - nechávám nezkonfigurované
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by samnazarko** [comment]
Are you still having problems?

**Comment by 2senel** [comment]
Just tried apt-get update and ended with black screen. After reboot still stuck on black screen, can't ssh too. 
One Pi was running Alpha 2, kernel update was OK, however device ended messed up.
Second Pi with Alpha 3, kernel update failed, ended up with black screen too.

**Comment by samnazarko** [comment]
Can you provide any logs or console outut?

**Comment by 2senel** [comment]
This is the latest console output I have from Alpha 3 PI :http://pastebin.com/yX06XvzM.
However, kernel dialog with Yes/No was immediately skipped and ended up with error.

Both devices are now unusable,  or at least, I don't how to get any logs from themy if can't connect to them via SSH and screen shows nothing.

**Comment by samnazarko** [comment]
The issue should be resolved now.

**Comment by 2senel** [comment]
So I reinstalled Alpha 3 on one Pi and did apt-get update (http://pastebin.com/uG7MwGJn). It ended with different error. However, after reboot I can connect to Pi via SSH besides the black screen which is still there.
