### ISSUE TITLE
Video Calibration not workin

### ISSUE THREAD

**Issue by tadeubanzato** [samnazarko/osmc#81]
Video Calibration not working properly, when change positions nothing changes on screen.
Subtitles position not working either.

**Comment by samnazarko** [comment]
Can you get a debug log of this?

**Comment by tadeubanzato** [comment]
How do i do that!

**Comment by samnazarko** [comment]
Hi

Please see the Wiki for how to upload logs:

https://osmc.tv/help/wiki/

You need to enable debugging in Kodi and then upload /home/pi/.kodi/temp/kodi.log

**Comment by samnazarko** [comment]
Resolved
