### ISSUE TITLE
Installer not working

### ISSUE THREAD

**Issue by vilinfield** [samnazarko/osmc#85]
The installer for osmc on Linux does not let you select what version to install so you cant install the system. Also there are many 503 errors on your website as well. Is there a direct link to download disk images? (Mainlly the latest build for the raspberry pi **not** pi2)

**Comment by vilinfield** [comment]
This is the error on the website for your information:

```
Error 503 Service Unavailable

Service Unavailable

Guru Meditation:

XID: 2047083455

Varnish cache server
```

**Comment by samnazarko** [comment]
Hi

This was caused by a lot of traffic on our website. This should mostly be resolved for now

Sam
