### ISSUE TITLE
OSMC Installer: removable drive detection failed on Gentoo Linux

### ISSUE THREAD

**Issue by aegypius** [samnazarko/osmc#87]
Hi, I tried to install osmc on my Raspberry Pi from a Gentoo Linux Host. 

I know this distribution is not (yet ;)) supported by the installer but I used the debian package and everything works as expected until the installer ask me to select my SDCard device.

It was not listed under the device list but all my other drives was listed. After trying to plug/unplug several time the card reader, I notice that the list of device was filtered in this file [installer/host/qt_host_installer/io_linux.cpp#L46](https://github.com/samnazarko/osmc/blob/757e60ed9814dc4b541d7957e83429596203ac98/installer/host/qt_host_installer/io_linux.cpp#L46)

My card reader was mapped to ```/dev/sda``` (I use LVM to manage my system drives).

I don't know if this is only my setup that is leading to this behavior or if other user could have this.

But I think, it would be better to read ```/sys/block/*/removable``` to check if device is removable.

In my system :

```
$> grep 1 /sys/block/*/removable | xargs dirname
/sys/block/sda
```

**Comment by srmo** [comment]
Thanks for this detailed report. We are about to rework device filtering in the installer. We'll post you once there's A

**Comment by samnazarko** [comment]
I think that 5d53a152668c7861bc7fab02e7530852fca2156e should handle this behaviour better.

Can you try it now? I have rebuilt the Debian package

**Comment by aegypius** [comment]
Thanks for the update, I will not be able to test this until tomorrow but as soon as I will keep you up-to-date

**Comment by aegypius** [comment]
It worked, I thanks a lot for your help !
