### ISSUE TITLE
GNU GPLv2

### ISSUE THREAD

**Issue by BobSheep** [samnazarko/osmc#93]
In the QT host installer you are required to accept the GNU GPL before installing.

The GNU GPL does not require you to accept the licence to use the software (Clauses 0 and 5). I would suggest changing this to something simple informing the user of their modification/redistribution rights as the GPL places no restrictions on use of the software.

https://github.com/samnazarko/osmc/blob/master/installer/host/qt_host_installer/licenseagreement.cpp

**Comment by samnazarko** [comment]
You are indeed right. I will remove this, but keep the box and change it to an EULA that ensures the user acknowledges OSMC comes with no implied warranty

**Comment by samnazarko** [comment]
Fixed
