### ISSUE TITLE
Slow WiFi (r8188eu)

### ISSUE THREAD

**Issue by He4dShOt** [samnazarko/osmc#96]
I can't get more than 50 KB/sec and I think something's wrong with the driver because I've tried with a windows machine and it's working fine.

I wanted to try compiling another version but I can't because there's a problem with the headers:

./arch/arm/include/asm/memory.h:24:25: fatal error: mach/memory.h: No such file or directory
 #include <mach/memory.h>

**Comment by samnazarko** [comment]
We include the headers in our APT repo, but don't install them by default.

I am aware of WiFi driver issues and am trying to improve the situation

Sam

**Comment by He4dShOt** [comment]
I got that message after installing the headers (rbp-headers-3.18.5-2-osmc).

**Comment by samnazarko** [comment]
I will investigate this.

**Comment by samnazarko** [comment]
Headers seem fine now.

**Comment by nikunjlahoti** [comment]
Hey Sam, I found this on Google. I am not sure if I should open another thread/bug here. I am trying to do this exactly thing and it's failing. I installed the headers too but mach/memory.h is something I couldn't resolve. Would you be able to tell me how to do that?

**Comment by nikunjlahoti** [comment]
I am currently on 4.4.16-1-osmc.
